### ISSUE TITLE
Dot plot 

### ISSUE THREAD

**Issue by TonnieKlappe** [okviz/DotPlot#2]
Hello,

Is it possible to change the X and the Y axis in the Dot Plot visual?

**Comment by danieleperilli** [comment]
It is possible to change their appearance and the Start/End of the Y axis.

**Comment by speedie7** [comment]
oke, but with this version can it be done and how?
like a stacked bar chart, i want it, not as a stack column chart.

**Comment by danieleperilli** [comment]
This is not the right chart, sorry.
